version: '3.7'

services:
  # nginx - web server
  nginx:
    build:
      context: .
      dockerfile: ./docker-config/nginx/Dockerfile
    env_file: &env
      - ./env/.env
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/project/app/public:cached
  # php - personal home page
  php:
    build:
      context: .
      dockerfile: ./docker-config/alpine-php-dev-overlay/Dockerfile
    depends_on:
      - "pgsql"
    env_file:
      *env
    expose:
      - "9000"
    links:
      - pgsql
    volumes:
        - ./:/var/www/project:consistent
        #      - ./app/vendor:/var/www/project/app/vendor:delegated
        #- ./app/var/logs:/var/www/project/app/var/logs:delegated
        #- ./app/var/cache:/var/www/project/app/var/cache:delegated
  # postgre - database
  pgsql:
    build:
      context: .
      dockerfile: ./docker-config/postgre/Dockerfile
    env_file: 
      - ./env/.env-pgsql
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: project
      POSTGRES_DB: project
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/pgsql
    restart: unless-stopped

volumes:
  db-data:
